
#
#

name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


env:
  VPS_ADMIN_USERNAME: aadmin
  DOCKER_REGISTRY_HOSTNAME: docker.addicticks.com
  DOCKER_REGISTRY_USERNAME: admin
  IMAGENAME: addicticks-outbound-email
  K8S_NAMESPACE: outbound-email

jobs:
  deploy:
    runs-on: 'ubuntu-20.04' # Match the version with the Google Distroless image we use

    steps:
      - uses: actions/checkout@v3

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'

      - name: Build native executable
        run: mvn -Pnative package

      - name: Docker build
        run: |
          docker build -t lbruun/tsid-k8s-instance-id .
          docker run lbruun/tsid-k8s-instance-id

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: docker push lbruun/tsid-k8s-instance-id

